<?php

define('LIFTOFF_DOMAIN', '.liftoff.albatrossdigital.com');
define('LIFTOFF_KEY', 'Z4lSpQl1YS7Mk4xX');
define('LIFTOFF_SIGNATURE', 'XQslWIHKxuorhtmlvtFAZaqFeeVAQZcB');


/**
 * Maps profile machine names to aegir nid.
 * This could be done in liftoff_api.module (on aegir).
 */
function _liftoff_api_profiles($profile) {
  $profiles = array(
    'liftoff' => 558,
    'helm' => 235,
  );
  return $profiles[$profile];
}


/**
 * Implementation of hook_menu()
 */
function liftoff_api_menu() {
  $items = array();

  $items['liftoff/api'] = array(
    'title' => 'List',
    //'page arguments' => array(2),
    'access callback' => 'liftoff_api_access',
    'page callback' => 'liftoff_api_callback',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Access callback.
 */
function liftoff_api_access() {
  return $_GET['key'] == LIFTOFF_KEY && $_GET['signature'] == LIFTOFF_SIGNATURE;
}


/**
 * API callback.
 */
function liftoff_api_callback() {
  $data = $_GET;
  $action = $data['action'];

  switch ($action) {
    case 'create':
    case 'clone':
      return liftoff_api_create($data);
      break;    
    case 'status':
      return node_load($data['nid']);
      break;
  }
}



function liftoff_api_create($data) {
  $url = !empty($data['machine_name']) ? $data['machine_name'] . LIFTOFF_DOMAIN : NULL;
  $node = new stdClass();
  $node->created = time();
  $node->changed = $node->created;
  $node->status = 1;
  $node->name = 'liftoffadmin'; // superuser
  $node->site_data = array('clients' => array(1=>0));
  
  switch ($data['action']) {
    case 'create':     
      $node->type = 'site';
      $node->client = 1; // Main aegir user. @todo: create new user with bakery?
      $node->db_server = 4;
      $node->name = '';  
      $node->platform = 416; // liftoff
      $node->profile = !empty($data['profile']) ? _liftoff_api_profiles($data['profile']) : 558; // liftoff=558, helm=235, standard=
      $node->title = $url;
      $node->hosting_name = $url;
      $node->site_status = 0;
      $node->verified = 0;
      $node->last_cron = 0;
      $node->cron_key = 0;
      $node->site_language = 'en';
      $node->cron_interval = 86400;
      $node->liftoff = (object) array(
        'user' => $data['user'],
        'mail' => $data['mail'],
        'role' => !empty($data['role']) ? $data['role'] : 'administrator',
        'lat' => !empty($data['lat']) ? $data['lat'] : NULL,
        'lng' => !empty($data['lng']) ? $data['lng'] : NULL,
      ); 
      break;


    case 'clone':
      $source_node = node_load($data['nid']);
      if ($source_node->type == 'site') {
        $node->type = 'task';
        $node->task_type = 'clone';
        $node->task_status = 0;
        $node->title = 'Clone ' . $source_node->title;
        $node->rid = $source_node->nid;
        $node->task_args = array(
          'new_uri' => $url,
          'new_db_server' => $source_node->db_server,
          'target_platform' => $source_node->platform,
        );
      }

      break;
  }

  if (!empty($node->type) && $node = node_submit($node)) {
    node_save($node);
    hosting_site_data_update($node);
    $return = array('node' => $node->nid);
  } else {
    $node = FALSE;
  }


  print drupal_json($node);
 
}



/**
 * Implementation of hook_insert().
 */
function liftoff_api_insert($node) {
  if ($node->type == 'site' && !empty($node->liftoff)) {
    $result = db_query("INSERT INTO {liftoff_api_site_data}
      (vid, nid, user, mail, role, lat, lng)
      VALUES (%d, %d, %s', '%s', '%s', '%s')",
      $node->vid,
      $node->nid, 
      $node->liftoff->name,
      $node->liftoff->mail,
      !empty($node->liftoff->role) ? $node->liftoff->role : 'administrator',
      !empty($node->liftoff->lat) ? $node->liftoff->lat : NULL,
      !empty($node->liftoff->lng) ? $node->liftoff->lng : NULL
    );

  }
}

/*
 * For some reason hook_post_hosting_install_task() wasn't working,
 * so this is called in hosting_site.drush.inc.
 */

function liftoff_api_post_hosting_install_task($task, $data) {
  if ($task->ref->type == 'site') {
    watchdog('albatross', '$task liftoff_api_post_hosting_install_task <pre>!a</pre>', array('!a' => print_r($task, 1)));
    watchdog('albatross', '$data liftoff_api_post_hosting_install_task <pre>!a</pre>', array('!a' => print_r($task->ref, 1)));
    $node = new stdClass();
    # copy some of the settings of the cloned site ($task->ref) to $task
    foreach (array('type', 'status', 'uid', 'rid', 'comment', 'promote', 'moderate', 'sticky', 'name', 'format', 'client', 'db_server', 'profile', 'site_status', 'site_language') as $field) {
      $node->$field = $task->$field;
    }
    $result = db_query("SELECT * FROM {liftoff_api_site_data} WHERE nid=%d",
      $task->ref->nid
    );
      watchdog('albatross', 'RESULT liftoff_api_post_hosting_install_task <pre>!a</pre>', array('!a' => print_r($result, 1)));

    $node->title = 'Add user: ' . $task->title;
    $node->task_type = 'add_user';
    $node->task_args = array(
      'user' => 'jeff',
      'mail' => 'jeff@albatrossdigital.com',
      'role' => 'administrator',
    );
      watchdog('albatross', '$new_task1 liftoff_api_post_hosting_install_task <pre>!a</pre>', array('!a' => print_r($node, 1)));

    node_save($node);
    watchdog('albatross', '$new_task liftoff_api_post_hosting_install_task <pre>!a</pre>', array('!a' => print_r($node, 1))); 
  }


}


function liftoff_api_pre_hosting_task($task) {
  watchdog('albatross', 'TASK liftoff_api_pre_hosting_task <pre>!a</pre>', array('!a' => print_r($task, 1)));
  $task =& drush_get_context('HOSTING_TASK');
  if ($task->ref->type == 'site' && $task->task_type == 'add_user') {
    $task->args[2] = $task->task_args['user'];
    $task->args[3] = $task->task_args['mail'];
    $task->args[4] = $task->task_args['role'];
  }
}